version: '3'

services: 
    backend:
        restart: always
        build: backend
        ports: 
            - 9000:9000
    frontend:
        restart: always
        stdin_open: true
        build: frontend
        ports:
            - 3000:3000
        depends_on: 
            - backend
